
# SQLALCHEMY_DATABASE_URL = "postgresql://myuser:1234@fastapi_postgres_1:5432/fastapi_database"

SQLALCHEMY_DATABASE_URL = "mariadb+pymysql://root:Snex2022@127.0.0.1:3306/hackat"
SECRET_KEY = 'VKNURGVDOUSYGRUYGVUISYAGOUYGERUdIYGN#^&@&&#DG&G&OGI&GA&WDG&IGD&*@GDSUBZioWMDEWDI@&YDN&I#EGDGEDAJXGMAGDUAEGDYEWU#^^*'