"""2

Revision ID: 238fb39d4096
Revises: 29d70ae4dfe0
Create Date: 2022-11-25 22:06:50.257811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238fb39d4096'
down_revision = '29d70ae4dfe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('male', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'male')
    op.drop_column('images', 'age')
    # ### end Alembic commands ###
